# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0.4'
gem 'mongo', '~> 2.6'
gem 'thin', '~> 1.7.2'