# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra', '~> 2.0', '>= 2.0.3'
gem 'redis', '~> 4.0', '>= 4.0.1'