---
# Source: flights-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flights-api
  labels:
    name: flights-api
spec:
  type: "LoadBalancer"
  ports:
  - name: http
    port: 3003
    targetPort: 3003
  selector:
    app: flights-api
---
# Source: flights-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "flights-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights-api
  template:
    metadata:
      labels:
        app: flights-api
    spec:
      containers:
        - image: "acrhackfestbrianredmond16005.azurecr.io/hackfest/flights-api:1.0"
          imagePullPolicy: Always
          name: flights-api
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: appinsights
            - name: DATA_SERVICE_URI
              value: http://data-api.hackfest.svc.cluster.local:3009/
            - name: CACHE_SERVICE_URI
              value: http://cache-api.hackfest.svc.cluster.local:3006/       
          ports:
          - containerPort: 3003
            protocol: TCP
      restartPolicy: Always
