---
# Source: weather-api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: weather-api
  labels:
    name: weather-api
spec:
  type: "LoadBalancer"
  ports:
  - name: http
    port: 3015
    targetPort: 3015
  selector:
    app: weather-api
---
# Source: weather-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "weather-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - image: "acrhackfestbrianredmond16005.azurecr.io/hackfest/weather-api:1.0"
          imagePullPolicy: Always
          name: weather-api
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: cosmos-db-secret
                  key: appinsights
            - name: DATA_SERVICE_URI
              value: http://data-api.hackfest.svc.cluster.local:3009/
            - name: CACHE_SERVICE_URI
              value: http://cache-api.hackfest.svc.cluster.local:3006/       
          ports:
          - containerPort: 3015
            protocol: TCP
      restartPolicy: Always
