kind: DaemonSet
apiVersion: apps/v1
metadata:
  labels:
    app: l7-log-collector
  name: l7-log-collector
  namespace: calico-system
spec:
  selector:
    matchLabels:
      app: l7-log-collector
  template:
    metadata:
      labels:
        app: l7-log-collector
      name: l7-log-collector
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostIPC: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: envoy-proxy
        image: quay.io/tigera/envoy:v3.9.0
        command: ["envoy", "-c", "/etc/envoy/envoy-config.yaml"]
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
          runAsUser: 0
          runAsGroup: 0
        env:
        - name: ENVOY_UID
          value: '0'
        - name: ENVOY_GID
          value: '0'
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
        - name: envoy-logs
          mountPath: /tmp/
      - name: l7-collector
        image: quay.io/tigera/l7-collector:v3.9.0
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: "Trace"
        - name: FELIX_DIAL_TARGET
          value: "/var/run/felix/nodeagent/socket"
        volumeMounts:
        - name: envoy-logs
          mountPath: /tmp/
        - name: felix-sync
          mountPath: /var/run/felix
      imagePullSecrets:
      - name: tigera-pull-secret
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
      - name: envoy-logs
        emptyDir: {}
      - name: felix-sync
        flexVolume:
          driver: nodeagent/uds

