kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: file-sc
provisioner: pxd.portworx.com
parameters:
  repl: "2"
  priority_io: "high"
  sharedv4: "true"
  sharedv4_svc_type: "ClusterIP"
  sharedv4_failover_strategy: "aggressive"