apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: pxd.portworx.com
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-restoredvol
spec:
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mongodb-pvc
    namespace: trashcan
  accessModes:
    - ReadWriteOnce
  storageClassName: trash-sc
  persistentVolumeReclaimPolicy: Retain
  portworxVolume:
    volumeID: "$TCVolId"