apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: security.frontend-nodeport-access
spec:
  tier: security
  order: 100
  selector: has(eks.amazonaws.com/nodegroup)
  # Allow all traffic to localhost.
  ingress:
  - action: Allow
    destination:
      nets:
      - 127.0.0.1/32
  # Allow node port access only from specific CIDR.
  - action: Deny
    protocol: TCP
    source:
      notNets:
      - ${CLOUD9_IP}
    destination:
      ports:
      - 30080
  doNotTrack: false
  applyOnForward: true
  preDNAT: true
  types:
    - Ingress
