def  appName = 'service-track-ui'
def  feSvcName = "${appName}"
def  ACRFOLDER = 'hackfest'
def  ACRNAME = 'tugboatlabs'
def  ACRURL = 'azurecr.io'
def  imageTag = "tugboatlabs.azurecr.io/${ACRFOLDER}/${appName}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"

pipeline {
  agent {
    kubernetes {
      label 'aks-hackfest'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
# Use service account that can deploy to all namespaces
  serviceAccountName: jenkins-jenkins
  containers:
  - name: helm
    image: lachlanevenson/k8s-helm:latest
    command:
    - cat
    tty: true
  - name: azurecli
    image: microsoft/azure-cli:latest
    command:
    - cat
    tty: true
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:latest
    command:
    - cat
    tty: true
"""
}
  }
  stages {

    
    stage('Build Container and Push to Registry') {
      steps {
        container('azurecli') {
        withCredentials([azureServicePrincipal('azurecli')]) {
            sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
            sh 'az account set -s $AZURE_SUBSCRIPTION_ID'
            sh("az acr build -t ${imageTag} -r ${ACRNAME}.${ACRURL} /app/service-tracker-ui")
        }
      }
     }
    }
    
    stage('Deploy To Production') {
      // Production branch
      steps{
        container('helm') {
        // Change deployed image to the one we just built
          sh("sed -i.bak 's#acrhackfestbrian13322.azurecr.io#${ACRNAME}.${ACRURL}#' ./app/charts/service-tracker-ui/values.yaml")
          sh("sed -i.bak 's#v1#${imageTag}#' ./app/charts/service-tracker-ui/values.yaml"
          sh("helm upgrade -f ./app/charts/service-tracker-ui")
          sh("echo http://`kubectl --namespace=production get service/${feSvcName} -o jsonpath='{.status.loadBalancer.ingress[0].ip}'` > ${feSvcName}")
        }
      }
    }
  }
}
