apiVersion: stork.libopenstorage.org/v1alpha1
kind: GroupVolumeSnapshot
metadata:
  name: mysql-group-snapshot
spec:
  preExecRule: mysql-presnap-rule
  postExecRule: mysql-postsnap-rule
  pvcSelector:
    matchLabels:
      app: mysql